# Generated by Django 4.2.11 on 2024-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('age', models.IntegerField()),
                ('sal', models.FloatField()),
                ('address', models.CharField(max_length=56)),
            ],
        ),
    ]
